import Head from "next/head";
import React from "react";
import { Box } from "@mui/material";
import UploadPhotos from "../components/account/UploadPhotos";

function AddProfilePhoto() {
  return (
    <>
      <Head>
        <title>Profile-Photo | My-house-help</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <UploadPhotos />
      </Box>
    </>
  );
}
export default AddProfilePhoto;
