import Head from 'next/head'
import React from 'react'
import DraweLayout from '../components/Reusable/DrawerLayout'

function drawer() {
  return (
    <>
         <Head>
        <title>Account | My-house-help</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <DraweLayout/>
      </Head>
    </>
  )
}

export default drawer