import Head from "next/head";
import HomePage from "../components/HomePage";
import { Box } from "@mui/material";


export default function Home() {
  return (
    <>
      <Head>
        <title>Home | House Help</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <HomePage />
      </Box>
    </>
  );
}
