import  Box  from '@mui/material'
import Head from 'next/head'
import React from 'react'
import styles from '@/styles/Home.module.css'
import UserProfile from '../components/account/UserProfile'

function User() {
  return (
    <>
       <Head>
        <title>My account | My-house-help</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         <main className={`${styles.main}`}>
        <UserProfile/>
      </main>
    </>
  )
}

export default User