import Head from "next/head";
import React from "react";
import styles from "@/styles/Home.module.css";
import UserAccount from "@/src/components/UserAccount";
import { Box } from "@mui/material";

function User({ singleUser }) {
  console.log("test single", singleUser);
  return (
    <>
      <Head>
        <title>User-Account | My-house-help</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <UserAccount singleUser={singleUser} />
      </Box>
    </>
  );
}

export default User;

export async function getServerSideProps({ req, query }) {
  const { singleUser } = query;
  console.log("data tesing", singleUser);

  return {
    props: {
      singleUser: singleUser || "",
    },
  };
}
