import Head from "next/head";
import React from "react";
import styles from "@/styles/Home.module.css";
import UserAccount from "@/src/components/UserAccount";

function User() {
  return (
    <>
      <Head>
        <title>User-Account | My-house-help</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <UserAccount />
      </main>
    </>
  );
}

export default User;
